"""
Django settings for vigiaa project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from datetime import timedelta
import environ  # Importa o django-environ
import platform

# 1. Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 2. Inicializa o environment manager
env = environ.Env(
    # Define tipos padrão caso a variável não exista no .env
    DEBUG=(bool, False) 
)

# 3. Lê o arquivo .env localizado na raiz do projeto (Formato universal Path)
environ.Env.read_env(BASE_DIR / '.env')

# Diretórios base do projeto de forma dinâmica
MEDIA_ROOT = BASE_DIR / 'media'
STATIC_ROOT = BASE_DIR / 'staticfiles'
TEMPLATE_DIR = BASE_DIR / 'templates'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='django-insecure-padrao-caso-nao-tenha-no-env')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

# Hosts permitidos dinâmicos (puxa o IP atual da máquina via .env se necessário)
ALLOWED_HOSTS = ["localhost", "127.0.0.1", "192.168.70.74", "desktop-m6ukbn7.local"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.gis',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "corsheaders",
    "casos",    
    "rest_framework",    
]

SESSION_COOKIE_SAMESITE = "Lax"

# Origens de CORS dinâmicas mapeando localhost, IP e o Hostname local
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://192.168.70.74:5173",
    "http://desktop-m6ukbn7.local:5173"
]

CORS_ALLOW_CREDENTIALS = True

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Celery Config vindo do .env
CELERY_BROKER_URL = env('CELERY_BROKER_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND', default='redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_TASK_ALWAYS_EAGER = True

ROOT_URLCONF = 'vigiaa.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR],  # Apontado para a sua variável dinâmica TEMPLATE_DIR
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'vigiaa.wsgi.application'


# Bancos de Dados dinâmicos usando dj-database-url mapeado direto do seu .env
# (Evita expor usuário e senha fixos no código do repositório)
import dj_database_url

DATABASES = {
    'default': dj_database_url.config(
        env='DATABASE_URL_TEMP',
        default='postgis://postgres:postgres@localhost:5432/vigiaa_temp'
    ),
    'oficial': dj_database_url.config(
        env='DATABASE_URL_OFC',
        default='postgis://postgres:postgres@localhost:5432/vigiaa_ofc'
    ),
}

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),  
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),  
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'  # Ajustado para o padrão brasileiro

TIME_ZONE = 'America/Sao_Paulo'  # Ajustado para o fuso horário local de SC

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Configuração Automática e Universal do GeoDjango (Windows vs Linux)
if platform.system() == "Windows":
    GDAL_LIBRARY_PATH = r'C:\Users\geati\AppData\Local\Programs\OSGeo4W\bin\gdal312.dll'
    GEOS_LIBRARY_PATH = r'C:\Users\geati\AppData\Local\Programs\OSGeo4W\bin\geos_c.dll'
    os.environ['PATH'] = r'C:\Users\geati\AppData\Local\Programs\OSGeo4W;' + ';' + os.environ.get('PATH', '')
else:
    # No Linux (Ubuntu), o GeoDjango localiza as bibliotecas .so automaticamente 
    # desde que o pacote gdal-bin esteja instalado globalmente no sistema.
    pass