# Generated by Django 6.0.1 on 2026-02-03 17:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armadilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=100)),
                ('localidade', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=150)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('quarteiroes', models.CharField(max_length=50)),
                ('tipo_imovel', models.CharField(max_length=50)),
                ('tipo_armadilha', models.CharField(max_length=50)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4674)),
            ],
            options={
                'db_table': 'relat_arm',
            },
        ),
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField()),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CasoPositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_atendimento', models.CharField(blank=True, max_length=100, null=True)),
                ('inicio_sintomas', models.DateField(blank=True, null=True)),
                ('notificacao', models.DateField(blank=True, null=True)),
                ('sinan', models.IntegerField(blank=True, null=True)),
                ('bairro', models.CharField(blank=True, max_length=50, null=True)),
                ('data_nasc', models.DateField(blank=True, null=True)),
                ('observacoes', models.CharField(blank=True, max_length=255, null=True)),
                ('resultado', models.CharField(blank=True, max_length=50, null=True)),
                ('aplicacao', models.CharField(blank=True, max_length=50, null=True)),
                ('agentes', models.CharField(blank=True, max_length=100, null=True)),
                ('prim_visita', models.CharField(blank=True, max_length=50, null=True)),
                ('situacao', models.CharField(blank=True, max_length=255, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4674)),
            ],
            options={
                'db_table': 'casos_positivos',
            },
        ),
        migrations.CreateModel(
            name='Foco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_foco', models.CharField(max_length=30)),
                ('localidade', models.CharField(max_length=100)),
                ('imovel', models.CharField(max_length=50)),
                ('deposito', models.CharField(max_length=100)),
                ('tipo_atividade', models.CharField(max_length=50)),
                ('data_coleta', models.DateField()),
                ('a_aegypti_form_aquaticas', models.IntegerField()),
                ('a_aegypti_form_adultas', models.IntegerField()),
                ('a_albopictus_form_aquaticas', models.IntegerField()),
                ('a_albopictus_form_adultas', models.IntegerField()),
                ('ovo_a_aegypti', models.IntegerField()),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4674)),
            ],
            options={
                'db_table': 'focos_aedes',
            },
        ),
        migrations.CreateModel(
            name='Importacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('hash', models.CharField(max_length=64)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PontoEstrategico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=100)),
                ('localidade', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=150)),
                ('quarteiroes', models.CharField(max_length=50)),
                ('complemento', models.CharField(max_length=100)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4674)),
            ],
            options={
                'db_table': 'pontos_estrategicos',
            },
        ),
    ]
