# Generated by Django 6.0.1 on 2026-01-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasoPositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=255)),
                ('data_notificacao', models.DateField()),
                ('sinan', models.CharField(max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
