# Generated by Django 6.0.1 on 2026-02-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0002_casopositivo_hash_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='armadilha',
            name='hash_registro',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='foco',
            name='hash_registro',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='pontoestrategico',
            name='hash_registro',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='casopositivo',
            name='hash_registro',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='armadilha',
            constraint=models.UniqueConstraint(condition=models.Q(('hash_registro__isnull', False)), fields=('hash_registro',), name='uq_relat_arm_hash_registro'),
        ),
        migrations.AddConstraint(
            model_name='casopositivo',
            constraint=models.UniqueConstraint(condition=models.Q(('hash_registro__isnull', False)), fields=('hash_registro',), name='uq_casos_positivos_hash_registro'),
        ),
        migrations.AddConstraint(
            model_name='foco',
            constraint=models.UniqueConstraint(condition=models.Q(('hash_registro__isnull', False)), fields=('hash_registro',), name='uq_focos_aedes_hash_registro'),
        ),
        migrations.AddConstraint(
            model_name='pontoestrategico',
            constraint=models.UniqueConstraint(condition=models.Q(('hash_registro__isnull', False)), fields=('hash_registro',), name='uq_pontos_estrategicos_hash_registro'),
        ),
    ]
