# Generated by Django 6.0.1 on 2026-02-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0002_casopositivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Armadilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_armadilha', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Foco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_foco', models.CharField(max_length=50)),
                ('data_coleta', models.DateField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PontoEstrategico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
