# Generated by Django 6.0.1 on 2026-02-02 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0003_armadilha_foco_pontoestrategico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Importacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('hash', models.CharField(max_length=64)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
