# Generated by Django 6.0.1 on 2026-02-10 18:02

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0003_armadilha_hash_registro_foco_hash_registro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArmadilhaTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=50, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('localidade', models.CharField(blank=True, max_length=100, null=True)),
                ('endereco', models.CharField(blank=True, max_length=150, null=True)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('quarteiroes', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_imovel', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_armadilha', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('hash_registro', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'relat_arm_temp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArmadilhaTempGL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=50, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('localidade', models.CharField(blank=True, max_length=100, null=True)),
                ('endereco', models.CharField(blank=True, max_length=150, null=True)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('quarteiroes', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_imovel', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_armadilha', models.CharField(blank=True, max_length=50, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4674)),
                ('hash_registro', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'relat_arm_temp_gl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CasoPositivoTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_atendimento', models.CharField(blank=True, max_length=100, null=True)),
                ('inicio_sintomas', models.DateField(blank=True, null=True)),
                ('notificacao', models.DateField(blank=True, null=True)),
                ('sinan', models.IntegerField(blank=True, null=True)),
                ('bairro', models.CharField(blank=True, max_length=50, null=True)),
                ('data_nasc', models.DateField(blank=True, null=True)),
                ('observacoes', models.CharField(blank=True, max_length=255, null=True)),
                ('resultado', models.CharField(blank=True, max_length=50, null=True)),
                ('aplicacao', models.CharField(blank=True, max_length=50, null=True)),
                ('agentes', models.CharField(blank=True, max_length=100, null=True)),
                ('prim_visita', models.CharField(blank=True, max_length=50, null=True)),
                ('situacao', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('hash_registro', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'casos_positivos_temp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CasoPositivoTempGL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_atendimento', models.CharField(blank=True, max_length=100, null=True)),
                ('inicio_sintomas', models.DateField(blank=True, null=True)),
                ('notificacao', models.DateField(blank=True, null=True)),
                ('sinan', models.IntegerField(blank=True, null=True)),
                ('bairro', models.CharField(blank=True, max_length=50, null=True)),
                ('data_nasc', models.DateField(blank=True, null=True)),
                ('observacoes', models.CharField(blank=True, max_length=255, null=True)),
                ('resultado', models.CharField(blank=True, max_length=50, null=True)),
                ('aplicacao', models.CharField(blank=True, max_length=50, null=True)),
                ('agentes', models.CharField(blank=True, max_length=100, null=True)),
                ('prim_visita', models.CharField(blank=True, max_length=50, null=True)),
                ('situacao', models.CharField(blank=True, max_length=255, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4674)),
                ('hash_registro', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'casos_positivos_temp_gl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FocoTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_foco', models.CharField(blank=True, max_length=30, null=True)),
                ('localidade', models.CharField(blank=True, max_length=100, null=True)),
                ('imovel', models.CharField(blank=True, max_length=50, null=True)),
                ('deposito', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_atividade', models.CharField(blank=True, max_length=50, null=True)),
                ('data_coleta', models.DateField(blank=True, null=True)),
                ('a_aegypti_form_aquaticas', models.IntegerField(blank=True, null=True)),
                ('a_aegypti_form_adultas', models.IntegerField(blank=True, null=True)),
                ('a_albopictus_form_aquaticas', models.IntegerField(blank=True, null=True)),
                ('a_albopictus_form_adultas', models.IntegerField(blank=True, null=True)),
                ('ovo_a_aegypti', models.IntegerField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('hash_registro', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'focos_aedes_temp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FocoTempGL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_foco', models.CharField(blank=True, max_length=30, null=True)),
                ('localidade', models.CharField(blank=True, max_length=100, null=True)),
                ('imovel', models.CharField(blank=True, max_length=50, null=True)),
                ('deposito', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_atividade', models.CharField(blank=True, max_length=50, null=True)),
                ('data_coleta', models.DateField(blank=True, null=True)),
                ('a_aegypti_form_aquaticas', models.IntegerField(blank=True, null=True)),
                ('a_aegypti_form_adultas', models.IntegerField(blank=True, null=True)),
                ('a_albopictus_form_aquaticas', models.IntegerField(blank=True, null=True)),
                ('a_albopictus_form_adultas', models.IntegerField(blank=True, null=True)),
                ('ovo_a_aegypti', models.IntegerField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4674)),
                ('hash_registro', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'focos_aedes_temp_gl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PontoEstrategicoTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=50, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('localidade', models.CharField(blank=True, max_length=100, null=True)),
                ('endereco', models.CharField(blank=True, max_length=150, null=True)),
                ('quarteiroes', models.CharField(blank=True, max_length=50, null=True)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('hash_registro', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'pontos_estrategicos_temp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PontoEstrategicoTempGL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=50, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('localidade', models.CharField(blank=True, max_length=100, null=True)),
                ('endereco', models.CharField(blank=True, max_length=150, null=True)),
                ('quarteiroes', models.CharField(blank=True, max_length=50, null=True)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4674)),
                ('hash_registro', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'pontos_estrategicos_temp_gl',
                'managed': False,
            },
        ),
    ]
