# Generated by Django 6.0.1 on 2026-03-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0004_armadilhatemp_armadilhatempgl_casopositivotemp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='iniciando', max_length=50)),
                ('progresso', models.IntegerField(default=0)),
                ('mensagem', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ArmadilhaTempGL',
        ),
        migrations.DeleteModel(
            name='FocoTempGL',
        ),
        migrations.DeleteModel(
            name='PontoEstrategicoTempGL',
        ),
    ]
