# Generated by Django 6.0.1 on 2026-05-04 16:49

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0005_processamento_delete_armadilhatempgl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogSincronizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('hash', models.CharField(max_length=64)),
                ('status', models.CharField(default='iniciando', max_length=50)),
                ('progresso', models.IntegerField(default=0)),
                ('mensagem', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'logs_sincronizacao',
            },
        ),
        migrations.DeleteModel(
            name='Importacao',
        ),
        migrations.DeleteModel(
            name='Processamento',
        ),
        migrations.AddField(
            model_name='casopositivo',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='casopositivo',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='casopositivo',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='casopositivo',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, editable=False, null=True, srid=4674),
        ),
        migrations.AlterField(
            model_name='casopositivo',
            name='hash_registro',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, null=True),
        ),
    ]
